module.exports={
  authController:require('./authController'),
  dashboardController:require('./dashboardController'),
  ordersController:require('./ordersController'),
  productsController:require('./productsController'),
  salesReportController:require('./salesReportController'),
  customersController:require('./customersController'),
  couponsController:require('./couponsController.js'),
  categoriesController:require('./categoriesController'),
  referralsController:require('./referralsController'),
}
